//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCIDENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCIDENTE()
        {
            this.REGISTRO_ACCIDENTADOS = new HashSet<REGISTRO_ACCIDENTADOS>();
        }
    
        public decimal ID_ACCIDENTE { get; set; }
        public System.DateTime FECHA_ACCIDENTE { get; set; }
    
        public virtual TIPO_ACCIDENTE TIPO_ACCIDENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_ACCIDENTADOS> REGISTRO_ACCIDENTADOS { get; set; }
    }
}
