//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCIDENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCIDENTE()
        {
            this.ASESORIA = new HashSet<ASESORIA>();
        }
    
        public long ID { get; set; }
        public string NATURALEZA { get; set; }
        public string PARTES_ACCIDENTADAS { get; set; }
        public string FUENTE_ACCIDENTE { get; set; }
        public System.DateTime FECHA_ACCIDENTE { get; set; }
        public long RUT_CLIENTE_ID { get; set; }
    
        public virtual AUTH_USER AUTH_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASESORIA> ASESORIA { get; set; }
    }
}
