//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTES_ASESORIA
    {
        public long ID { get; set; }
        public string DESCRIPCION_DOCUMENTO { get; set; }
        public string DOCUMENTO { get; set; }
        public long ID_ASESORIA_ID { get; set; }
        public long ASESORIA_ID { get; set; }
    
        public virtual ASESORIA ASESORIA { get; set; }
        public virtual ASESORIA ASESORIA1 { get; set; }
    }
}
