//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASESORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASESORIA()
        {
            this.ANTECEDENTES_ASESORIA = new HashSet<ANTECEDENTES_ASESORIA>();
        }
    
        public decimal ID_ASESORIA { get; set; }
        public string EVENTO { get; set; }
        public string PROPUESTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANTECEDENTES_ASESORIA> ANTECEDENTES_ASESORIA { get; set; }
        public virtual VISITA_TERRENO VISITA_TERRENO { get; set; }
    }
}
