//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASESORIA
    {
        public long ID { get; set; }
        public string EVENTO { get; set; }
        public string PROPUESTA { get; set; }
        public string ASESORIA_ESPECIAL { get; set; }
        public Nullable<long> ID_ACCIDENTE_ID { get; set; }
        public Nullable<long> ID_FISCALIZACION_ID { get; set; }
    
        public virtual ACCIDENTE ACCIDENTE { get; set; }
        public virtual FISCALIZACION FISCALIZACION { get; set; }
    }
}
