//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DjangoEntities : DbContext
    {
        public DjangoEntities()
            : base("name=DjangoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCIDENTE> ACCIDENTE { get; set; }
        public virtual DbSet<ACCOUNT_USERPROFILE> ACCOUNT_USERPROFILE { get; set; }
        public virtual DbSet<ANTECEDENTES_ASESORIA> ANTECEDENTES_ASESORIA { get; set; }
        public virtual DbSet<ASESORIA> ASESORIA { get; set; }
        public virtual DbSet<AUTH_GROUP> AUTH_GROUP { get; set; }
        public virtual DbSet<AUTH_GROUP_PERMISSIONS> AUTH_GROUP_PERMISSIONS { get; set; }
        public virtual DbSet<AUTH_PERMISSION> AUTH_PERMISSION { get; set; }
        public virtual DbSet<AUTH_USER> AUTH_USER { get; set; }
        public virtual DbSet<AUTH_USER_GROUPS> AUTH_USER_GROUPS { get; set; }
        public virtual DbSet<AUTH_USER_USER_PERMISSIONS> AUTH_USER_USER_PERMISSIONS { get; set; }
        public virtual DbSet<CAPACITACION> CAPACITACION { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<DJANGO_ADMIN_LOG> DJANGO_ADMIN_LOG { get; set; }
        public virtual DbSet<DJANGO_CONTENT_TYPE> DJANGO_CONTENT_TYPE { get; set; }
        public virtual DbSet<DJANGO_MIGRATIONS> DJANGO_MIGRATIONS { get; set; }
        public virtual DbSet<DJANGO_SESSION> DJANGO_SESSION { get; set; }
        public virtual DbSet<INFORME_VISITA> INFORME_VISITA { get; set; }
        public virtual DbSet<MATERIAL_CAPACITACIONES> MATERIAL_CAPACITACIONES { get; set; }
        public virtual DbSet<MATERIAL_SOLICITADO> MATERIAL_SOLICITADO { get; set; }
        public virtual DbSet<MATERIAL_SOLICITADO_ID> MATERIAL_SOLICITADO_ID_MAT9F2C { get; set; }
        public virtual DbSet<MULTA> MULTA { get; set; }
        public virtual DbSet<REGISTRO_ACCIDENTADOS> REGISTRO_ACCIDENTADOS { get; set; }
        public virtual DbSet<REGISTRO_PAGOS> REGISTRO_PAGOS { get; set; }
        public virtual DbSet<TIPO_ACCIDENTE> TIPO_ACCIDENTE { get; set; }
        public virtual DbSet<TIPO_CONTRATO> TIPO_CONTRATO { get; set; }
        public virtual DbSet<VISITA_TERRENO> VISITA_TERRENO { get; set; }
    
        public virtual int PRC_LISTAR_CLIENTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_CLIENTE");
        }
    
        public virtual int PRC_LISTAR_TRABAJADORES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_TRABAJADORES");
        }
    }
}
