//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME_VISITA
    {
        public long ID { get; set; }
        public string INTRODUCCION { get; set; }
        public string RESULTADOS_EVALUACION { get; set; }
        public string AUTOEVALUACION { get; set; }
        public string DOC_ACTUALIZADOS { get; set; }
        public string REG_INTERNO { get; set; }
        public string DOC_SEREMI_TRABAJO { get; set; }
        public string COPIA_DOCUMENTOS { get; set; }
        public string INFORMA_RIESGOS { get; set; }
        public string INFORMA_MEDIDAS { get; set; }
        public string PROGRAMA_ORDEN { get; set; }
        public string EXTINTORES { get; set; }
        public string CAPACITACION_EXTINTOR { get; set; }
        public string EPP_INVENTARIO { get; set; }
        public string EPP_CERTIFICADOS { get; set; }
        public long ID_VISITA_ID { get; set; }
        public long VISITA_TERRENO_ID { get; set; }
    
        public virtual VISITA_TERRENO VISITA_TERRENO { get; set; }
        public virtual VISITA_TERRENO VISITA_TERRENO1 { get; set; }
    }
}
