//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_SOLICITADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIAL_SOLICITADO()
        {
            this.MATERIAL_SOLICITADO_ID_MAT9F2C = new HashSet<MATERIAL_SOLICITADO_ID>();
        }
    
        public long ID { get; set; }
        public long CANTIDAD { get; set; }
        public long ID_CAPACITACION_ID { get; set; }
        public long CAPACITACION_ID { get; set; }
        public long MATERIAL_ID { get; set; }
    
        public virtual CAPACITACION CAPACITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIAL_SOLICITADO_ID> MATERIAL_SOLICITADO_ID_MAT9F2C { get; set; }
        public virtual CAPACITACION CAPACITACION1 { get; set; }
        public virtual MATERIAL_CAPACITACIONES MATERIAL_CAPACITACIONES { get; set; }
    }
}
