//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_PAGOS
    {
        public decimal ID_PAGO { get; set; }
        public decimal MONTO_PAGO { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
