//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCIDENTE> ACCIDENTE { get; set; }
        public virtual DbSet<ANTECEDENTES_ASESORIA> ANTECEDENTES_ASESORIA { get; set; }
        public virtual DbSet<ASESORIA> ASESORIA { get; set; }
        public virtual DbSet<CAPACITACION> CAPACITACION { get; set; }
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<INFORME_VISITA> INFORME_VISITA { get; set; }
        public virtual DbSet<MATERIAL_CAPACITACIONES> MATERIAL_CAPACITACIONES { get; set; }
        public virtual DbSet<MATERIAL_SOLICITADO> MATERIAL_SOLICITADO { get; set; }
        public virtual DbSet<MULTA> MULTA { get; set; }
        public virtual DbSet<REGISTRO_ACCIDENTADOS> REGISTRO_ACCIDENTADOS { get; set; }
        public virtual DbSet<REGISTRO_PAGOS> REGISTRO_PAGOS { get; set; }
        public virtual DbSet<TIPO_ACCIDENTE> TIPO_ACCIDENTE { get; set; }
        public virtual DbSet<TIPO_CONTRATO> TIPO_CONTRATO { get; set; }
        public virtual DbSet<TRABAJADOR> TRABAJADOR { get; set; }
        public virtual DbSet<VISITA_TERRENO> VISITA_TERRENO { get; set; }
    }
}
