//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SafeDjangoEntities : DbContext
    {
        public SafeDjangoEntities()
            : base("name=SafeDjangoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCIDENTE> ACCIDENTE { get; set; }
        public virtual DbSet<ACCOUNT_USERPROFILE> ACCOUNT_USERPROFILE { get; set; }
        public virtual DbSet<ASESORIA> ASESORIA { get; set; }
        public virtual DbSet<AUTH_GROUP> AUTH_GROUP { get; set; }
        public virtual DbSet<AUTH_GROUP_PERMISSIONS> AUTH_GROUP_PERMISSIONS { get; set; }
        public virtual DbSet<AUTH_PERMISSION> AUTH_PERMISSION { get; set; }
        public virtual DbSet<AUTH_USER> AUTH_USER { get; set; }
        public virtual DbSet<AUTH_USER_GROUPS> AUTH_USER_GROUPS { get; set; }
        public virtual DbSet<AUTH_USER_USER_PERMISSIONS> AUTH_USER_USER_PERMISSIONS { get; set; }
        public virtual DbSet<CAPACITACION> CAPACITACION { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<COSTO_ADICIONAL> COSTO_ADICIONAL { get; set; }
        public virtual DbSet<DJANGO_ADMIN_LOG> DJANGO_ADMIN_LOG { get; set; }
        public virtual DbSet<DJANGO_CONTENT_TYPE> DJANGO_CONTENT_TYPE { get; set; }
        public virtual DbSet<DJANGO_MIGRATIONS> DJANGO_MIGRATIONS { get; set; }
        public virtual DbSet<DJANGO_SESSION> DJANGO_SESSION { get; set; }
        public virtual DbSet<FISCALIZACION> FISCALIZACION { get; set; }
        public virtual DbSet<INFORME_VISITA> INFORME_VISITA { get; set; }
        public virtual DbSet<MATERIAL_CAPACITACIONES> MATERIAL_CAPACITACIONES { get; set; }
        public virtual DbSet<MATERIAL_SOLICITADO> MATERIAL_SOLICITADO { get; set; }
        public virtual DbSet<MULTA> MULTA { get; set; }
        public virtual DbSet<REGISTRO_PAGOS> REGISTRO_PAGOS { get; set; }
        public virtual DbSet<VISITA_TERRENO> VISITA_TERRENO { get; set; }
    
        public virtual int PRC_INSERTAR_ASESORIA_ACCIDENTE(string v_PROPUESTA, Nullable<decimal> v_ID_ACCIDENTE, ObjectParameter v_SALIDA)
        {
            var v_PROPUESTAParameter = v_PROPUESTA != null ?
                new ObjectParameter("V_PROPUESTA", v_PROPUESTA) :
                new ObjectParameter("V_PROPUESTA", typeof(string));
    
            var v_ID_ACCIDENTEParameter = v_ID_ACCIDENTE.HasValue ?
                new ObjectParameter("V_ID_ACCIDENTE", v_ID_ACCIDENTE) :
                new ObjectParameter("V_ID_ACCIDENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_ASESORIA_ACCIDENTE", v_PROPUESTAParameter, v_ID_ACCIDENTEParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_ASESORIA_FISCALIZACION(string v_PROPUESTA, Nullable<decimal> v_ID_FISCALIZACION_ID, ObjectParameter v_SALIDA)
        {
            var v_PROPUESTAParameter = v_PROPUESTA != null ?
                new ObjectParameter("V_PROPUESTA", v_PROPUESTA) :
                new ObjectParameter("V_PROPUESTA", typeof(string));
    
            var v_ID_FISCALIZACION_IDParameter = v_ID_FISCALIZACION_ID.HasValue ?
                new ObjectParameter("V_ID_FISCALIZACION_ID", v_ID_FISCALIZACION_ID) :
                new ObjectParameter("V_ID_FISCALIZACION_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_ASESORIA_FISCALIZACION", v_PROPUESTAParameter, v_ID_FISCALIZACION_IDParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_CAPACITACION(string v_HORA_CAPACITACION, Nullable<decimal> v_RUT_CLIENTE, Nullable<decimal> v_RUT_TRABAJADOR, ObjectParameter v_SALIDA)
        {
            var v_HORA_CAPACITACIONParameter = v_HORA_CAPACITACION != null ?
                new ObjectParameter("V_HORA_CAPACITACION", v_HORA_CAPACITACION) :
                new ObjectParameter("V_HORA_CAPACITACION", typeof(string));
    
            var v_RUT_CLIENTEParameter = v_RUT_CLIENTE.HasValue ?
                new ObjectParameter("V_RUT_CLIENTE", v_RUT_CLIENTE) :
                new ObjectParameter("V_RUT_CLIENTE", typeof(decimal));
    
            var v_RUT_TRABAJADORParameter = v_RUT_TRABAJADOR.HasValue ?
                new ObjectParameter("V_RUT_TRABAJADOR", v_RUT_TRABAJADOR) :
                new ObjectParameter("V_RUT_TRABAJADOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_CAPACITACION", v_HORA_CAPACITACIONParameter, v_RUT_CLIENTEParameter, v_RUT_TRABAJADORParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_CLIENTE(string v_USUARIO, string v_PASS, string v_NOMBRE, string v_APELLIDO, string v_CORREO, ObjectParameter v_SALIDA)
        {
            var v_USUARIOParameter = v_USUARIO != null ?
                new ObjectParameter("V_USUARIO", v_USUARIO) :
                new ObjectParameter("V_USUARIO", typeof(string));
    
            var v_PASSParameter = v_PASS != null ?
                new ObjectParameter("V_PASS", v_PASS) :
                new ObjectParameter("V_PASS", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_APELLIDOParameter = v_APELLIDO != null ?
                new ObjectParameter("V_APELLIDO", v_APELLIDO) :
                new ObjectParameter("V_APELLIDO", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_CLIENTE", v_USUARIOParameter, v_PASSParameter, v_NOMBREParameter, v_APELLIDOParameter, v_CORREOParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_DATOS_CLIENTE(Nullable<decimal> v_RUT, Nullable<decimal> v_SUELDO, Nullable<decimal> v_EDAD, Nullable<decimal> v_USERID, ObjectParameter v_SALIDA)
        {
            var v_RUTParameter = v_RUT.HasValue ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(decimal));
    
            var v_SUELDOParameter = v_SUELDO.HasValue ?
                new ObjectParameter("V_SUELDO", v_SUELDO) :
                new ObjectParameter("V_SUELDO", typeof(decimal));
    
            var v_EDADParameter = v_EDAD.HasValue ?
                new ObjectParameter("V_EDAD", v_EDAD) :
                new ObjectParameter("V_EDAD", typeof(decimal));
    
            var v_USERIDParameter = v_USERID.HasValue ?
                new ObjectParameter("V_USERID", v_USERID) :
                new ObjectParameter("V_USERID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_DATOS_CLIENTE", v_RUTParameter, v_SUELDOParameter, v_EDADParameter, v_USERIDParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_DATOS_TRABAJADOR(Nullable<decimal> v_RUT, Nullable<decimal> v_SUELDO, Nullable<decimal> v_EDAD, Nullable<decimal> v_USERID, ObjectParameter v_SALIDA)
        {
            var v_RUTParameter = v_RUT.HasValue ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(decimal));
    
            var v_SUELDOParameter = v_SUELDO.HasValue ?
                new ObjectParameter("V_SUELDO", v_SUELDO) :
                new ObjectParameter("V_SUELDO", typeof(decimal));
    
            var v_EDADParameter = v_EDAD.HasValue ?
                new ObjectParameter("V_EDAD", v_EDAD) :
                new ObjectParameter("V_EDAD", typeof(decimal));
    
            var v_USERIDParameter = v_USERID.HasValue ?
                new ObjectParameter("V_USERID", v_USERID) :
                new ObjectParameter("V_USERID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_DATOS_TRABAJADOR", v_RUTParameter, v_SUELDOParameter, v_EDADParameter, v_USERIDParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_FISCALIZACION(string v_DOC_REVISADOS, string v_DESCRIPCION_DOCUMENTO, string v_DOCUMENTO, string v_RUT_CLIENTE_ID, ObjectParameter v_SALIDA)
        {
            var v_DOC_REVISADOSParameter = v_DOC_REVISADOS != null ?
                new ObjectParameter("V_DOC_REVISADOS", v_DOC_REVISADOS) :
                new ObjectParameter("V_DOC_REVISADOS", typeof(string));
    
            var v_DESCRIPCION_DOCUMENTOParameter = v_DESCRIPCION_DOCUMENTO != null ?
                new ObjectParameter("V_DESCRIPCION_DOCUMENTO", v_DESCRIPCION_DOCUMENTO) :
                new ObjectParameter("V_DESCRIPCION_DOCUMENTO", typeof(string));
    
            var v_DOCUMENTOParameter = v_DOCUMENTO != null ?
                new ObjectParameter("V_DOCUMENTO", v_DOCUMENTO) :
                new ObjectParameter("V_DOCUMENTO", typeof(string));
    
            var v_RUT_CLIENTE_IDParameter = v_RUT_CLIENTE_ID != null ?
                new ObjectParameter("V_RUT_CLIENTE_ID", v_RUT_CLIENTE_ID) :
                new ObjectParameter("V_RUT_CLIENTE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_FISCALIZACION", v_DOC_REVISADOSParameter, v_DESCRIPCION_DOCUMENTOParameter, v_DOCUMENTOParameter, v_RUT_CLIENTE_IDParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_INFORME_VISITA(string v_INTRODUCCION, string v_RESULTADOS_EVALUACION, string v_AUTOEVALUACION, string v_DOC_ACTUALIZADOS, string v_REG_INTERNO, string v_DOC_SEREMI_TRABAJO, string v_COPIA_DOCUMENTOS, string v_INFORMA_RIESGOS, string v_INFORMA_MEDIDAS, string v_PROGRAMA_ORDEN, string v_EXTINTORES, string v_CAPACITACION_EXTINTOR, string v_EPP_INVENTARIO, string v_EPP_CERTIFICADOS, Nullable<decimal> v_ID_VISITA_ID, ObjectParameter v_SALIDA)
        {
            var v_INTRODUCCIONParameter = v_INTRODUCCION != null ?
                new ObjectParameter("V_INTRODUCCION", v_INTRODUCCION) :
                new ObjectParameter("V_INTRODUCCION", typeof(string));
    
            var v_RESULTADOS_EVALUACIONParameter = v_RESULTADOS_EVALUACION != null ?
                new ObjectParameter("V_RESULTADOS_EVALUACION", v_RESULTADOS_EVALUACION) :
                new ObjectParameter("V_RESULTADOS_EVALUACION", typeof(string));
    
            var v_AUTOEVALUACIONParameter = v_AUTOEVALUACION != null ?
                new ObjectParameter("V_AUTOEVALUACION", v_AUTOEVALUACION) :
                new ObjectParameter("V_AUTOEVALUACION", typeof(string));
    
            var v_DOC_ACTUALIZADOSParameter = v_DOC_ACTUALIZADOS != null ?
                new ObjectParameter("V_DOC_ACTUALIZADOS", v_DOC_ACTUALIZADOS) :
                new ObjectParameter("V_DOC_ACTUALIZADOS", typeof(string));
    
            var v_REG_INTERNOParameter = v_REG_INTERNO != null ?
                new ObjectParameter("V_REG_INTERNO", v_REG_INTERNO) :
                new ObjectParameter("V_REG_INTERNO", typeof(string));
    
            var v_DOC_SEREMI_TRABAJOParameter = v_DOC_SEREMI_TRABAJO != null ?
                new ObjectParameter("V_DOC_SEREMI_TRABAJO", v_DOC_SEREMI_TRABAJO) :
                new ObjectParameter("V_DOC_SEREMI_TRABAJO", typeof(string));
    
            var v_COPIA_DOCUMENTOSParameter = v_COPIA_DOCUMENTOS != null ?
                new ObjectParameter("V_COPIA_DOCUMENTOS", v_COPIA_DOCUMENTOS) :
                new ObjectParameter("V_COPIA_DOCUMENTOS", typeof(string));
    
            var v_INFORMA_RIESGOSParameter = v_INFORMA_RIESGOS != null ?
                new ObjectParameter("V_INFORMA_RIESGOS", v_INFORMA_RIESGOS) :
                new ObjectParameter("V_INFORMA_RIESGOS", typeof(string));
    
            var v_INFORMA_MEDIDASParameter = v_INFORMA_MEDIDAS != null ?
                new ObjectParameter("V_INFORMA_MEDIDAS", v_INFORMA_MEDIDAS) :
                new ObjectParameter("V_INFORMA_MEDIDAS", typeof(string));
    
            var v_PROGRAMA_ORDENParameter = v_PROGRAMA_ORDEN != null ?
                new ObjectParameter("V_PROGRAMA_ORDEN", v_PROGRAMA_ORDEN) :
                new ObjectParameter("V_PROGRAMA_ORDEN", typeof(string));
    
            var v_EXTINTORESParameter = v_EXTINTORES != null ?
                new ObjectParameter("V_EXTINTORES", v_EXTINTORES) :
                new ObjectParameter("V_EXTINTORES", typeof(string));
    
            var v_CAPACITACION_EXTINTORParameter = v_CAPACITACION_EXTINTOR != null ?
                new ObjectParameter("V_CAPACITACION_EXTINTOR", v_CAPACITACION_EXTINTOR) :
                new ObjectParameter("V_CAPACITACION_EXTINTOR", typeof(string));
    
            var v_EPP_INVENTARIOParameter = v_EPP_INVENTARIO != null ?
                new ObjectParameter("V_EPP_INVENTARIO", v_EPP_INVENTARIO) :
                new ObjectParameter("V_EPP_INVENTARIO", typeof(string));
    
            var v_EPP_CERTIFICADOSParameter = v_EPP_CERTIFICADOS != null ?
                new ObjectParameter("V_EPP_CERTIFICADOS", v_EPP_CERTIFICADOS) :
                new ObjectParameter("V_EPP_CERTIFICADOS", typeof(string));
    
            var v_ID_VISITA_IDParameter = v_ID_VISITA_ID.HasValue ?
                new ObjectParameter("V_ID_VISITA_ID", v_ID_VISITA_ID) :
                new ObjectParameter("V_ID_VISITA_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_INFORME_VISITA", v_INTRODUCCIONParameter, v_RESULTADOS_EVALUACIONParameter, v_AUTOEVALUACIONParameter, v_DOC_ACTUALIZADOSParameter, v_REG_INTERNOParameter, v_DOC_SEREMI_TRABAJOParameter, v_COPIA_DOCUMENTOSParameter, v_INFORMA_RIESGOSParameter, v_INFORMA_MEDIDASParameter, v_PROGRAMA_ORDENParameter, v_EXTINTORESParameter, v_CAPACITACION_EXTINTORParameter, v_EPP_INVENTARIOParameter, v_EPP_CERTIFICADOSParameter, v_ID_VISITA_IDParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_MATERIALES(string v_MATERIAL, ObjectParameter v_SALIDA)
        {
            var v_MATERIALParameter = v_MATERIAL != null ?
                new ObjectParameter("V_MATERIAL", v_MATERIAL) :
                new ObjectParameter("V_MATERIAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_MATERIALES", v_MATERIALParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_MATERIALES_SOLICITADOS(Nullable<decimal> v_ID_MATERIAL, Nullable<decimal> v_CANTIDAD, Nullable<decimal> v_CAPACITACION_ID, ObjectParameter v_SALIDA)
        {
            var v_ID_MATERIALParameter = v_ID_MATERIAL.HasValue ?
                new ObjectParameter("V_ID_MATERIAL", v_ID_MATERIAL) :
                new ObjectParameter("V_ID_MATERIAL", typeof(decimal));
    
            var v_CANTIDADParameter = v_CANTIDAD.HasValue ?
                new ObjectParameter("V_CANTIDAD", v_CANTIDAD) :
                new ObjectParameter("V_CANTIDAD", typeof(decimal));
    
            var v_CAPACITACION_IDParameter = v_CAPACITACION_ID.HasValue ?
                new ObjectParameter("V_CAPACITACION_ID", v_CAPACITACION_ID) :
                new ObjectParameter("V_CAPACITACION_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_MATERIALES_SOLICITADOS", v_ID_MATERIALParameter, v_CANTIDADParameter, v_CAPACITACION_IDParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_TRABAJADORES(string v_USUARIO, string v_PASS, string v_NOMBRE, string v_APELLIDO, string v_CORREO, ObjectParameter v_SALIDA)
        {
            var v_USUARIOParameter = v_USUARIO != null ?
                new ObjectParameter("V_USUARIO", v_USUARIO) :
                new ObjectParameter("V_USUARIO", typeof(string));
    
            var v_PASSParameter = v_PASS != null ?
                new ObjectParameter("V_PASS", v_PASS) :
                new ObjectParameter("V_PASS", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_APELLIDOParameter = v_APELLIDO != null ?
                new ObjectParameter("V_APELLIDO", v_APELLIDO) :
                new ObjectParameter("V_APELLIDO", typeof(string));
    
            var v_CORREOParameter = v_CORREO != null ?
                new ObjectParameter("V_CORREO", v_CORREO) :
                new ObjectParameter("V_CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_TRABAJADORES", v_USUARIOParameter, v_PASSParameter, v_NOMBREParameter, v_APELLIDOParameter, v_CORREOParameter, v_SALIDA);
        }
    
        public virtual int PRC_INSERTAR_VISITA(string v_MOTIVO, Nullable<System.DateTime> v_VISITA_FECHA, Nullable<decimal> v_RUT_CLIENTE, Nullable<decimal> v_RUT_TRABAJADOR, ObjectParameter v_SALIDA)
        {
            var v_MOTIVOParameter = v_MOTIVO != null ?
                new ObjectParameter("V_MOTIVO", v_MOTIVO) :
                new ObjectParameter("V_MOTIVO", typeof(string));
    
            var v_VISITA_FECHAParameter = v_VISITA_FECHA.HasValue ?
                new ObjectParameter("V_VISITA_FECHA", v_VISITA_FECHA) :
                new ObjectParameter("V_VISITA_FECHA", typeof(System.DateTime));
    
            var v_RUT_CLIENTEParameter = v_RUT_CLIENTE.HasValue ?
                new ObjectParameter("V_RUT_CLIENTE", v_RUT_CLIENTE) :
                new ObjectParameter("V_RUT_CLIENTE", typeof(decimal));
    
            var v_RUT_TRABAJADORParameter = v_RUT_TRABAJADOR.HasValue ?
                new ObjectParameter("V_RUT_TRABAJADOR", v_RUT_TRABAJADOR) :
                new ObjectParameter("V_RUT_TRABAJADOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_INSERTAR_VISITA", v_MOTIVOParameter, v_VISITA_FECHAParameter, v_RUT_CLIENTEParameter, v_RUT_TRABAJADORParameter, v_SALIDA);
        }
    
        public virtual int PRC_LISTAR_ACCIDENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_ACCIDENTES");
        }
    
        public virtual int PRC_LISTAR_ACCIDENTES_POR_ID(Nullable<decimal> v_RUT_CLIENTE_ID)
        {
            var v_RUT_CLIENTE_IDParameter = v_RUT_CLIENTE_ID.HasValue ?
                new ObjectParameter("V_RUT_CLIENTE_ID", v_RUT_CLIENTE_ID) :
                new ObjectParameter("V_RUT_CLIENTE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_ACCIDENTES_POR_ID", v_RUT_CLIENTE_IDParameter);
        }
    
        public virtual int PRC_LISTAR_ASESORIAS_POR_ID_ACCIDENTE(Nullable<decimal> v_ID_ACCIDENTE)
        {
            var v_ID_ACCIDENTEParameter = v_ID_ACCIDENTE.HasValue ?
                new ObjectParameter("V_ID_ACCIDENTE", v_ID_ACCIDENTE) :
                new ObjectParameter("V_ID_ACCIDENTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_ASESORIAS_POR_ID_ACCIDENTE", v_ID_ACCIDENTEParameter);
        }
    
        public virtual int PRC_LISTAR_CAPACITACIONES(Nullable<decimal> v_RUT_TRABAJADOR)
        {
            var v_RUT_TRABAJADORParameter = v_RUT_TRABAJADOR.HasValue ?
                new ObjectParameter("V_RUT_TRABAJADOR", v_RUT_TRABAJADOR) :
                new ObjectParameter("V_RUT_TRABAJADOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_CAPACITACIONES", v_RUT_TRABAJADORParameter);
        }
    
        public virtual int PRC_LISTAR_CLIENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_CLIENTES");
        }
    
        public virtual int PRC_LISTAR_CLIENTES_EXTENDIDOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_CLIENTES_EXTENDIDOS");
        }
    
        public virtual int PRC_LISTAR_FISCALIZACIONES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_FISCALIZACIONES");
        }
    
        public virtual int PRC_LISTAR_MATERIAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_MATERIAL");
        }
    
        public virtual int PRC_LISTAR_MATERIALES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_MATERIALES");
        }
    
        public virtual int PRC_LISTAR_TRABAJADORES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_TRABAJADORES");
        }
    
        public virtual int PRC_LISTAR_TRABAJADORES_EXTENDIDOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_TRABAJADORES_EXTENDIDOS");
        }
    
        public virtual int PRC_LISTAR_VISITAS_SIN_EXTENDER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_LISTAR_VISITAS_SIN_EXTENDER");
        }
    
        public virtual int PRC_MOSTRAR_DIA_CAPACITACION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_MOSTRAR_DIA_CAPACITACION");
        }
    
        public virtual int PRC_REPORTAR_ACCIDENTE(string v_NATURALEZA, string v_PARTES_ACCIDENTADAS, string v_FUENTE_ACCIDENTE_ID, Nullable<System.DateTime> v_FECHA_ACCIDENTE, Nullable<decimal> v_RUT_CLIENTE_ID, ObjectParameter v_SALIDA)
        {
            var v_NATURALEZAParameter = v_NATURALEZA != null ?
                new ObjectParameter("V_NATURALEZA", v_NATURALEZA) :
                new ObjectParameter("V_NATURALEZA", typeof(string));
    
            var v_PARTES_ACCIDENTADASParameter = v_PARTES_ACCIDENTADAS != null ?
                new ObjectParameter("V_PARTES_ACCIDENTADAS", v_PARTES_ACCIDENTADAS) :
                new ObjectParameter("V_PARTES_ACCIDENTADAS", typeof(string));
    
            var v_FUENTE_ACCIDENTE_IDParameter = v_FUENTE_ACCIDENTE_ID != null ?
                new ObjectParameter("V_FUENTE_ACCIDENTE_ID", v_FUENTE_ACCIDENTE_ID) :
                new ObjectParameter("V_FUENTE_ACCIDENTE_ID", typeof(string));
    
            var v_FECHA_ACCIDENTEParameter = v_FECHA_ACCIDENTE.HasValue ?
                new ObjectParameter("V_FECHA_ACCIDENTE", v_FECHA_ACCIDENTE) :
                new ObjectParameter("V_FECHA_ACCIDENTE", typeof(System.DateTime));
    
            var v_RUT_CLIENTE_IDParameter = v_RUT_CLIENTE_ID.HasValue ?
                new ObjectParameter("V_RUT_CLIENTE_ID", v_RUT_CLIENTE_ID) :
                new ObjectParameter("V_RUT_CLIENTE_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_REPORTAR_ACCIDENTE", v_NATURALEZAParameter, v_PARTES_ACCIDENTADASParameter, v_FUENTE_ACCIDENTE_IDParameter, v_FECHA_ACCIDENTEParameter, v_RUT_CLIENTE_IDParameter, v_SALIDA);
        }
    }
}
